{% set version = "1.9.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  fn: google-cloud-storage-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: af3cdf4807f78d04b22fe89cbc8a129342d679932e8acecb02fdebde69f047f3

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - requests >=2.0.0

  run:
    - python
    - google-cloud-core >=0.28.0,<0.29dev
    - google-api-core >=0.1.1,<0.2.0dev
    - google-auth >=1.2.0
    - google-resumable-media >=0.3.1
    - requests >=2.18.0

test:
  imports:
    - google
    - google.cloud
    - google.cloud.storage

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  summary: Python Client for Google Cloud Storage
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-api.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
