{% set version = "1.37.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: 2003c5ed473f9b37d045f30c4c8be7d30d7d0eb8a97bcd2c58b3a8bc549c4ccc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - google-auth >=1.11.0,<2.0dev
    - google-cloud-core >=1.4.1,<2.0dev
    - google-resumable-media >=1.0.0,<2.0dev
    - yarl >=1.0,<1.6.0
    - requests >=2.18.0,<3.0.0dev
    - google-crc32c
    - python
    # Workaround for https://github.com/conda-forge/aiohttp-feedstock/issues/43
    - yarl <1.6.0,>=1.0

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  doc_url: https://googleapis.dev/python/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
