{% set name = "google-cloud-storage" %}
{% set version = "3.1.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_storage-{{ version }}.tar.gz
  sha256: 944273179897c7c8a07ee15f2e6466a02da0c7c4b9ecceac2a26017cb2972049

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - google-auth >=2.26.1,<3.0dev
    - google-api-core >=2.15.0,<3.0.0dev
    - google-cloud-core >=2.4.2,<3.0dev
    - google-resumable-media >=2.7.2
    - requests >=2.18.0,<3.0.0dev
    - google-crc32c >=1.0,<2.0dev
    - protobuf <6.0.0dev
  run_constrained:
    - opentelemetry-api >=1.1.0

test:
  requires:
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  description: |
    Python client for a durable and highly available object storage service.
    Google Cloud Storage is almost infinitely scalable and guarantees
    consistency; when a write succeeds, the latest copy of the object will
    be returned to any GET, globally.
  doc_url: https://cloud.google.com/python/docs/reference/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
