{% set name = "google-cloud-storage" %}
{% set version = "2.6.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 104ca28ae61243b637f2f01455cc8a05e8f15a2a18ced96cb587241cdd3820f5

build:
  number: 0
  # A lot of dependencies are not available on s390x currently  # [py<37 or s390x or ppc64le]
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - google-auth >=1.25.0,<3.0dev
    - google-api-core >=1.31.5,<3.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-cloud-core >=2.3.0,<3.0dev
    - google-resumable-media >=2.3.2
    - requests >=2.18.0,<3.0.0dev
    - protobuf <5.0.0dev

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  description: |
    Python client for a durable and highly available object storage service.
    Google Cloud Storage is almost infinitely scalable and guarantees
    consistency; when a write succeeds, the latest copy of the object will
    be returned to any GET, globally.
  doc_url: https://cloud.google.com/python/docs/reference/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  license_url: https://github.com/googleapis/python-storage/blob/main/LICENSE

extra:
  recipe-maintainers:
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
