{% set name = "google-cloud-storage" %}
{% set version = "2.17.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49378abff54ef656b52dca5ef0f2eba9aa83dc2b2c72c78714b03a1a95fe9388

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - google-auth >=2.26.1,<3.0dev
    - google-api-core >=2.15.0,<3.0.0dev
    - google-cloud-core >=2.3.0,<3.0dev
    - google-resumable-media >=2.6.0
    - requests >=2.18.0,<3.0.0dev
    - google-crc32c >=1.0,<2.0dev
    # protobuf extra
    - protobuf <5.0.0dev

test:
  requires:
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  description: |
    Python client for a durable and highly available object storage service.
    Google Cloud Storage is almost infinitely scalable and guarantees
    consistency; when a write succeeds, the latest copy of the object will
    be returned to any GET, globally.
  doc_url: https://cloud.google.com/python/docs/reference/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
