travis:
  secure:
    BINSTAR_TOKEN: CDKGPQ12ky0sxzMEoKNvsRJxDYsSljd0rbTt9skTZTI+p1worg7SNtn6fFRTBYAvWfj8TNfEytt+E14vAmLzOvoICOIN4bM/5WTCZvhu7kJCY8VX4ran88btp8eitbvMWxNDWCKfFjQP0GD0dOvafT1Ole6XQ36al+K8Va9FKXc9giV6s12RDB3Gn2V82wD18SRO4yKoYWLuDQ5Is8g6fhL+9zqOzHUALupRa7fUeVIu6YV9V1ihozSEQedS3gA8ON+vFoUzU7y2rAXHYsr0mSCMEN3vulBjU0X2vrwSFkm1EIoqLaRX2+SADB4jvrslBMa6KtiY15zKE446O3tPQCukXsVZGNMvTVJ6UrCnWGnS8WE/uhby+/dXWRvZavFhPXZCPLL0JfBD9/ez4A2phaK6KX9NVj2FSQbifE80U0CalRysCztash66g4Ur2/+/RWhPsAVyGxcz6ew1NIU+n7RCrxfZLweUbneV9Dad0f6gJ4xEDckJ/9zLJ5MWOiVcOk172CKe6VnwEVyXvqw4CU2N1wHC11mtlMr3ZT2zhW6Ocnxloc1uyq26VQi0oQdM3ptFIkH70aPyy7C1T5H5QQsPrDKkqWk0UBhs21iRy4n4DkLd3dBybworjnuVxR4Mo72A6Y4bNi1nuyrM3NKXVf3DKW+OyBGGaDLJZX2I3yY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
