travis:
  secure:
    BINSTAR_TOKEN: A8z6InS4HkI/yzi9e4stJ8Sq2d/8jgSKMHwoRQyZjXZ72F0ZmiAi5iVMf/Z1+Ntlh05WoyEkJ6Et5KIPLrlDi0/JsOeYoyNfs/iYoRRnwTVXrmcD3G5dDifsJhivfJsxDGeTaZHWQfQdpYQEYY1r3X68ZZ+zDcMFbCTi6SiJ2wfCET9OAbibnhLfO5KGkrv4K9yNRdmPz1IIOd9GmfVmJ1N8dQrJeFXBjVm5J5/k+jPz4t+k+0uDqkLnZJ+oGtWwxjMVn6BYKTb/ahQqFgTPK+06THbGCIt/IWQGZfvkkZX37CdVnxZVoOxdnj/3BOlkmosMMEHXhK+ef05wisVtrA0zrRgxfCPFWp5Xz394TG3+AE2mmXNd9mhtgW9cQrDWhb73tRSKSXNNTgGBbYX98BQ3PMrSKS9F6kB2PLPR/1yWgBIuMbCpLV+wTIS0DuE+azD10NdbR8zbxnw0ycAJWAorh1S1CMjZQcKZBwL4tPUekzHg5jYRvZEfNQk2DZRTtewbmpiKN+KkLX1qojrL6OOTshQd+/E3teTf+vzRNMx6pxj6Yeob04C3tgPuPIyqbl2u2iqRuxwJyMob44DXWbszfeHsdn8030NuLEUfA0m3aXjfIwKvHf66Jir4n6h/JeqSS9d2Gf5pECidovyFi33SanE8iEnbpV2EAPgxI5M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
