travis:
  secure:
    BINSTAR_TOKEN: ItcRWwvUYd0FU6jgS8Efcq7sp5Jfz0BWXdIiDVOnQjyAl2TR1qoejQDDigf33FTiCZiJpQ4P6XGZNcNOodaNH4vom7oLRRV3rvaSCvGD4B62iGzSXZOPw5oeijDShuea/VklxFwNF5BuASKUgsgnOeHmGEL7erDTaNWETaEQVYfCb9jEW3a+J61aNwPiUcRvYZFkcYudaK2cELytvPh/ZSSBvufqG/rHQKU4YMmk5rIxOewhJV02gpp1pT93oeoARbV9IG31E95FwL5umzqHWoqioA1uyxQDYvVK5qXNzG2TfM7B+LbddfbAzDMKwRJAVnzvg5LdsKMybghLzHKJ1gQ0KVTc84lwY7efMaGstQce5raD2a4/7VhFSy4dTzDN7/EOyjsyGZYjVrMNi9GjFexrGLBcJNsm+thNsqfhpcGeCAq7KfU5YPVzKrzxKqr3eWMldvTNxfUNBNphhV7m+DLh7UJzqBgTTD9gHGKCFp0zzkyUgkaSAg36Ff8v2yECYJwUfki3/6Cfl/KvaUB1t8JBsA36MYewF9IkZXjM3TQnD6/RfmKbiof010VO1sS/ZFxphEThQIHAUwZuXgo4v0vzSoYN5NGBdakQv3UpdpXLCvE0S7odvcQUPwzNgrduR46aPAsHNgcoCvju79HjjghdgkO5ep9GhcLOImAsETs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
